weatherapi.key=${WEATHER_API_KEY}
weatherapi.base-url=https://api.weatherapi.com/v1
weatherapi.location=CABA

spring.datasource.url=jdbc:h2:mem:climalert
spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=belardinelliluka@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true